import { useEffect, useRef, useState } from 'react'
import { ArrowDownRight, ArrowUp, BookOpen, ExternalLink, Menu, X } from 'lucide-react'
import { essay, market, project, references, team, t, type Language, type Localized } from './data/content'

const copy = {
  nav: { overview:['Overview','概览'], team:['Team','团队'], research:['Research','研究'], prototype:['Prototype','原型'], market:['Market','市场'], future:['Future','未来'], references:['References','参考文献'] },
  ui: { skip:['Skip to content','跳到主要内容'], menu:['Open navigation','打开导航'], close:['Close navigation','关闭导航'], language:['Choose language','选择语言'], explore:['Explore the project','探索项目'], read:['Read the research','阅读研究'], top:['Back to top','返回顶部'] }
} as const
const str = (pair: readonly [string,string], lang:Language) => pair[lang === 'en' ? 0 : 1]
function Heading({n,title,intro,lang}:{n:string;title:Localized;intro?:Localized;lang:Language}) { return <div className="heading"><span>{n}</span><div><h2>{t(title,lang)}</h2>{intro&&<p>{t(intro,lang)}</p>}</div></div> }

export default function App(){
  const [language,setLanguage]=useState<Language>(()=>{const saved=localStorage.getItem('mathzlet-language'); if(saved==='en'||saved==='zh-CN')return saved; return navigator.language.toLowerCase().startsWith('zh')?'zh-CN':'en'})
  const [open,setOpen]=useState(false); const menuButton=useRef<HTMLButtonElement>(null)
  useEffect(()=>{document.documentElement.lang=language; localStorage.setItem('mathzlet-language',language)},[language])
  useEffect(()=>{if(!open)return; const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);menuButton.current?.focus()}}; document.addEventListener('keydown',close); document.body.classList.add('menu-open'); return()=>{document.removeEventListener('keydown',close);document.body.classList.remove('menu-open')}},[open])
  const L=(value:Localized)=>t(value,language)
  const nav=Object.entries(copy.nav)
  return <>
    <a className="skip-link" href="#main">{str(copy.ui.skip,language)}</a>
    <header className="site-header"><a className="brand" href="#overview"><BookOpen size={19}/><span>Mathzlet</span></a>
      <nav className="desktop-nav" aria-label={language==='en'?'Primary':'主要导航'}>{nav.map(([id,label])=><a key={id} href={`#${id}`}>{str(label,language)}</a>)}</nav>
      <div className="header-tools"><div className="language" role="group" aria-label={str(copy.ui.language,language)}><button aria-pressed={language==='en'} onClick={()=>setLanguage('en')}>EN</button><button aria-pressed={language==='zh-CN'} onClick={()=>setLanguage('zh-CN')}>中文</button></div><button ref={menuButton} className="menu-button" aria-expanded={open} aria-controls="mobile-nav" aria-label={str(open?copy.ui.close:copy.ui.menu,language)} onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</button></div>
      <nav id="mobile-nav" className={`mobile-nav ${open?'is-open':''}`} aria-label={language==='en'?'Mobile navigation':'移动导航'}>{nav.map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{str(label,language)}</a>)}</nav>
    </header>
    <main id="main">
      <section className="hero" id="overview"><div><p className="kicker">{language==='en'?'Working digital prototype · Team 2':'可运行的数字原型 · Team 2'}</p><h1>Mathzlet</h1><p className="subtitle">{language==='en'?'Mathematics learning for children aged 5–6':'面向 5–6 岁儿童的数学学习项目'}</p><p className="thesis">{L(project.description)}</p><div className="actions"><a className="button primary" href="#project">{str(copy.ui.explore,language)} <ArrowDownRight size={17}/></a><a className="button secondary" href="#research">{str(copy.ui.read,language)}</a></div></div><aside><p>{language==='en'?'Design principle':'设计原则'}</p><strong>{L(project.tagline)}</strong><span>{language==='en'?'A team intention—not a proven advantage.':'团队的设计意图，而非已证实的优势。'}</span></aside></section>
      <section id="project"><Heading lang={language} n="01" title={{en:'Project overview','zh-CN':'项目概览'}} intro={{en:'A public view of the prototype without disclosing unreleased gameplay systems.','zh-CN':'在不披露未公开玩法系统的前提下介绍原型。'}}/><div className="facts">{[[language==='en'?'Age group':'年龄','5–6'],[language==='en'?'Format':'形式',language==='en'?'Website prototype':'网站原型'],[language==='en'?'Context':'当前背景',language==='en'?'China':'中国'],[language==='en'?'Languages':'语言',language==='en'?'English + Simplified Chinese':'英语 + 简体中文'],[language==='en'?'Mode':'模式',language==='en'?'Technically single-player':'技术上以单人模式为主'],[language==='en'?'Next directions':'未来方向',language==='en'?'App · Multiplayer · Physical cards':'应用 · 多人模式 · 实体卡牌']].map(([a,b])=><article key={a}><p>{a}</p><strong>{b}</strong></article>)}</div><div className="split"><article><h3>{language==='en'?'Why we created Mathzlet':'为什么创作 Mathzlet'}</h3><p>{language==='en'?'We share an interest in mathematics and want children to experience mathematical thinking through clear, age-appropriate interaction—not only memorized answers. Visual relationships and understandable guidance shape our direction.':'我们热爱数学，希望儿童通过清晰、适龄的互动体验数学思维，而不只是记忆答案。视觉关系和易懂的引导塑造了项目方向。'}</p></article><article><h3>{language==='en'?'Who we design for':'为谁而设计'}</h3><p>{language==='en'?'Children aged 5–6 are the primary users. Parents, caregivers, friends, and future teachers may support exploration. This website primarily serves families, educators, professors, evaluators, and course visitors.':'5–6 岁儿童是主要使用者；家长、照护者、朋友和未来的教师可以支持探索。本网站主要面向家庭、教育工作者、教授、项目评审和课程访客。'}</p></article></div></section>
      <section id="team"><Heading lang={language} n="02" title={{en:'Meet Team 2','zh-CN':'认识 Team 2'}} intro={{en:'We combine programming, research, design, data collection, and project organization to develop and improve Mathzlet.','zh-CN':'我们结合程序开发、研究、设计、资料收集和项目组织，共同开发并改进 Mathzlet。'}}/><div className="team-grid">{team.map(m=><article key={m.name}><div className="initials" aria-hidden="true">{m.initials}</div><p className="role">{L(m.roles)}</p><h3>{m.name}</h3><p>{L(m.description)}</p><span>{L(m.tags)}</span></article>)}</div></section>
      <section id="research"><Heading lang={language} n="03" title={{en:'Research summary','zh-CN':'研究概要'}} intro={{en:'Published research informs design questions; it does not establish that Mathzlet produces learning gains.','zh-CN':'已发表研究为设计问题提供依据，但不能证明 Mathzlet 已带来学习提升。'}}/><div className="research-grid">{[['Pattern recognition','模式识别'],['Logical reasoning','逻辑推理'],['Working memory','工作记忆'],['Inhibitory control','抑制控制'],['Cognitive flexibility','认知灵活性'],['Confidence & curiosity','信心与好奇心']].map(x=><article key={x[0]}><span>{language==='en'?'Academic research / project goal':'学术研究 / 项目目标'}</span><h3>{str(x as [string,string],language)}</h3></article>)}</div><article className="essay" aria-labelledby="essay-title"><p className="eyebrow">{language==='en'?'Full research essay':'完整研究文章'}</p><h2 id="essay-title">{language==='en'?'How Chinese Children Aged 5–6 Think About Mathematics':'中国 5–6 岁儿童如何理解数学'}</h2>{essay.map(s=><section key={s.title.en}><h3>{L(s.title)}</h3>{s.paragraphs.map(p=><p key={p.en}>{L(p)}</p>)}</section>)}<aside>{language==='en'?'Editorial note: This version is based on published educational research and is suitable for a school or university assignment.':'编辑说明：本版本以已发表的教育研究为基础，适合用于学校或大学作业。'}</aside></article></section>
      <section id="prototype"><Heading lang={language} n="04" title={{en:'From feedback to design','zh-CN':'从反馈走向设计'}} intro={{en:'Early qualitative feedback from a small number of children and preschool educators. It is not a representative study.','zh-CN':'来自少量儿童和幼儿教育工作者的早期定性反馈，并非具有代表性的研究。'}}/><div className="process"><article><span>01</span><h3>{language==='en'?'Observation':'观察'}</h3><p>{language==='en'?'Children struggled with text-heavy English instructions.':'儿童难以理解文字过多、以英语为主的指令。'}</p></article><article><span>02</span><h3>{language==='en'?'Interpretation':'解读'}</h3><p>{language==='en'?'The prototype required too much reading and language processing for the target age.':'原型对阅读和语言处理的要求超出了目标年龄段的适宜水平。'}</p></article><article><span>03</span><h3>{language==='en'?'Design response':'设计回应'}</h3><p>{language==='en'?'We reduced text, strengthened visual guidance, simplified instructions, and added bilingual support.':'我们减少文字、加强视觉引导、简化指令，并加入双语支持。'}</p></article></div><div className="notice"><strong>{language==='en'?'Further testing required':'仍需进一步测试'}</strong><p>{language==='en'?'The revised prototype responds directly to initial feedback, but further testing is still needed. Selected gameplay mechanics remain under development and are not yet publicly documented.':'修订后的原型已直接回应早期反馈，但仍需进一步测试。部分玩法机制仍在开发中，尚未公开。'}</p></div><Heading lang={language} n="05" title={{en:'Educational goals','zh-CN':'教育目标'}}/><div className="goals">{(language==='en'?['Foundational mathematics','Calculation confidence','Pattern recognition','Abstract thinking','Logical reasoning','Flexible strategies','Positive mathematical attitudes']:['基础数学能力','计算信心','模式识别','抽象思考','逻辑推理','灵活策略','积极的数学态度']).map(g=><span key={g}>{g}</span>)}</div></section>
      <section id="market"><Heading lang={language} n="06" title={{en:'Market landscape','zh-CN':'市场概览'}} intro={{en:'A concise qualitative comparison of public product descriptions. Listings describe features, not educational effectiveness.','zh-CN':'依据公开产品说明进行的简明定性比较。产品页面介绍功能，并不能证明教育成效。'}}/><div className="table-wrap" tabIndex={0} role="region" aria-label={language==='en'?'Scrollable competitor comparison':'可横向滚动的产品比较'}><table><thead><tr><th>{language==='en'?'Product':'产品'}</th><th>{language==='en'?'Age':'年龄'}</th><th>{language==='en'?'Approach':'方式'}</th><th>{language==='en'?'Platform / model':'平台 / 模式'}</th><th>{language==='en'?'Official source':'官方来源'}</th></tr></thead><tbody>{market.map(m=><tr key={m.name}><td><strong>{m.name}</strong></td><td>{m.age}</td><td>{L(m.approach)}</td><td>{L(m.platform)}</td><td><a href={m.url} target="_blank" rel="noopener noreferrer">{m.publisher} <ExternalLink size={14}/><span className="sr-only"> ({language==='en'?'opens in a new tab':'在新标签页打开'})</span></a></td></tr>)}</tbody></table></div><p className="source-note">{language==='en'?'Sources accessed 16 July 2026. Language support and mainland-China availability were not verified from the reviewed official pages. Mathzlet’s reduced-text, bilingual, caregiver-supported, digital-to-physical direction is a design intention—not a claim of superiority.':'来源访问日期：2026 年 7 月 16 日。所审阅的官方页面未能核实语言支持与中国大陆可用情况。Mathzlet 的少文字、双语、照护者支持以及数字到实体的发展方向是设计意图，并非优越性声明。'}</p></section>
      <section id="future"><Heading lang={language} n="07" title={{en:'Future plans','zh-CN':'未来计划'}}/><ul className="future-list">{(language==='en'?['Improve the current prototype and continue simplifying instructions','Conduct more structured testing with children aged 5–6','Gather more parent and teacher feedback','Develop a downloadable app and explore Google Play publication','Add multiplayer support and create a physical card-game version','Improve visual design, accessibility, and international support']:['改进当前原型并继续简化指令','与 5–6 岁儿童开展更有结构的测试','收集更多家长和教师反馈','开发可下载应用并探索在 Google Play 发布','加入多人支持并制作实体卡牌版本','改进视觉设计、无障碍体验和国际化支持']).map(x=><li key={x}>{x}</li>)}</ul><div className="ack"><h3>{language==='en'?'Acknowledgements':'致谢'}</h3><p>{language==='en'?'We thank Li, Fanny (an HKU professor and the team’s main teacher), and Shown for their support. This project was developed during a summer-course program associated with YunGu High School and Class 413, with participation from a student at Putai Senior High School.':'感谢 Li、Fanny（香港大学教授及团队主要教师）和 Shown 的支持。本项目在与 YunGu High School 和 Class 413 相关的暑期课程中开展，其中一名参与学生来自 Putai Senior High School。'}</p></div></section>
      <section id="references"><Heading lang={language} n="08" title={{en:'References','zh-CN':'参考文献'}} intro={{en:'Verified academic sources used in the research essay.','zh-CN':'研究文章中使用并已核实的学术来源。'}}/><div className="sources">{references.map((r,i)=><article key={r.id} id={`ref-${r.id}`}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{r.citation}</h3><p>{L(r.supports)}</p><a href={r.url} target="_blank" rel="noopener noreferrer">{language==='en'?'View source':'查看来源'} <ExternalLink size={14}/><span className="sr-only"> ({language==='en'?'opens in a new tab':'在新标签页打开'})</span></a></div></article>)}</div></section>
    </main><footer><p>Mathzlet · Team 2</p><p>{language==='en'?'Chinese project label is descriptive website copy, not a registered product name.':'中文项目名称为网站说明性译名，并非注册产品名称。'}</p><a href="#overview">{str(copy.ui.top,language)} <ArrowUp size={15}/></a></footer>
  </>
}

