import { ArrowDownRight, BookOpen, CircleAlert, ExternalLink } from 'lucide-react'
import { report } from './data/report'

const nav = ['summary', 'market', 'customers', 'analysis', 'competition', 'opportunity', 'evidence']

export default function App() {
  return <><header><a className="brand" href="#overview"><BookOpen size={19}/>Team {report.team} · Market research</a><nav>{nav.map(item => <a href={`#${item}`} key={item}>{item}</a>)}</nav></header><main>
    <section className="hero" id="overview"><div><p className="kicker">{report.status}</p><h1>{report.title}</h1><p className="subtitle">{report.subtitle}</p><p className="thesis">{report.thesis}</p><a className="text-link" href="#opportunity">Read recommendation <ArrowDownRight size={17}/></a></div><aside><p>Decision</p><strong>{report.decision}</strong><span>{report.date}</span></aside></section>
    <section id="summary"><Heading n="01" title="Decision summary" intro="Verified findings, directional proxies and outstanding unknowns are clearly separated."/><div className="stats">{report.stats.map(s=><article key={s.value}><p>{s.kind}</p><strong>{s.value}</strong><span>{s.label}</span></article>)}</div><div className="finding-grid">{report.findings.map((f,i)=><article key={f.title}><span>0{i+1}</span><h3>{f.title}</h3><p>{f.text}</p></article>)}</div></section>
    <section id="market"><Heading n="02" title="Market boundary" intro={report.scopeIntro}/><div className="two-col">{report.scope.map(s=><article key={s.title}><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
    <section id="customers"><Heading n="03" title="Users & buying context" intro={report.customerIntro}/><div className="finding-grid">{report.customers.map((c,i)=><article key={c.title}><span>0{i+1}</span><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
    <section id="analysis"><Heading n="04" title="Report analysis" intro="The full decision context from the supplied report, retained as narrative rather than compressed into metrics."/><div className="narrative">{report.narrative.map(item => <article key={item.title}><h3>{item.title}</h3>{item.paragraphs.map(p => <p key={p}>{p}</p>)}</article>)}</div></section>
    <section id="competition"><Heading n="05" title="Competitive landscape" intro={report.competitionIntro}/><div className="table-wrap"><table><thead><tr><th>Product / substitute</th><th>Positioning / offer</th><th>Evidence boundary</th></tr></thead><tbody>{report.competitors.map(c=><tr key={c[0]}>{c.map(x=><td key={x}>{x}</td>)}</tr>)}</tbody></table></div></section>
    <section id="opportunity"><Heading n="06" title="Opportunity & recommendation" intro={report.opportunityIntro}/><div className="recommendation"><p>Recommended next step</p><h2>{report.recommendation}</h2><ol>{report.nextSteps.map(x=><li key={x}>{x}</li>)}</ol></div></section>
    <section id="evidence"><Heading n="07" title="Evidence register" intro="Sources are carried from the supplied report. Missing links are labelled rather than invented."/><div className="sources">{report.sources.map(s=><article key={s.title}><div><h3>{s.title}</h3><p>{s.org}</p></div><div><span>{s.date}</span>{s.url ? <a href={s.url} target="_blank" rel="noreferrer">Source <ExternalLink size={14}/></a> : <span className="missing">Link not supplied <CircleAlert size={14}/></span>}</div></article>)}</div></section>
  </main><footer><p>Generated from the supplied Team {report.team} market research report.</p><span>Facts, estimates, proxies and assumptions remain distinguished throughout.</span></footer></>
}
function Heading({ n, title, intro }: { n:string; title:string; intro:string }) { return <div className="heading"><span>{n}</span><div><h2>{title}</h2><p>{intro}</p></div></div> }
